// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKmhTgP0gk84Fm0fAw3NEhvgU07wqWb4o',
    appId: '1:227243161896:web:c1c1ff24a7b2cff0be381d',
    messagingSenderId: '227243161896',
    projectId: 'aallycare-ca61b',
    authDomain: 'aallycare-ca61b.firebaseapp.com',
    storageBucket: 'aallycare-ca61b.firebasestorage.app',
    measurementId: 'G-RRGVNSVNDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRS2BZcymCdbiYXwZh_SQPAMUv3fWB3jg',
    appId: '1:227243161896:android:52ae115bcbd2a2f2be381d',
    messagingSenderId: '227243161896',
    projectId: 'aallycare-ca61b',
    storageBucket: 'aallycare-ca61b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRl7lEDvb09k10sKKINkgmWJl62WyvS9A',
    appId: '1:227243161896:ios:76cf10e244f17355be381d',
    messagingSenderId: '227243161896',
    projectId: 'aallycare-ca61b',
    storageBucket: 'aallycare-ca61b.firebasestorage.app',
    iosBundleId: 'com.example.aallycare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRl7lEDvb09k10sKKINkgmWJl62WyvS9A',
    appId: '1:227243161896:ios:76cf10e244f17355be381d',
    messagingSenderId: '227243161896',
    projectId: 'aallycare-ca61b',
    storageBucket: 'aallycare-ca61b.firebasestorage.app',
    iosBundleId: 'com.example.aallycare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKmhTgP0gk84Fm0fAw3NEhvgU07wqWb4o',
    appId: '1:227243161896:web:8787ed58f5f40f08be381d',
    messagingSenderId: '227243161896',
    projectId: 'aallycare-ca61b',
    authDomain: 'aallycare-ca61b.firebaseapp.com',
    storageBucket: 'aallycare-ca61b.firebasestorage.app',
    measurementId: 'G-MG0GRQW38F',
  );
}
